const economicSeasonal = [
	"Pandemic",
	"Endemic",
	"Recession",
	"Powell",
	"Biden",
	"Yellen",
];
const moneySeasonal = ["Saudi Wealth Fund", "Softbank Vision Fund"];
const techSeasonal = ["P2E"];

const commonEconomicMoney = ["Real estate", "Rent", "Inflation"];
const commonMoneyTech = [
	"Entrepreneurship",
	"Billionaire",
	"CEO",
	"Founder",
	"NFT",
];

export const mainCategoryOptions = ["Economic", "Money", "Tech"];
export const middleCategoryOptions: Record<
	(typeof mainCategoryOptions)[number],
	string[]
> = {
	Economic: [
		"FOMC",
		"Fed",
		"Bank of Korea",
		"Bank of America",
		"IMF",
		"WFP",
		"UN",
		"ILO",
		"World Bank",
		"WHO",
		"WTO",
		"APEC",
		"OECD",
		"EU",
		"ASEAN",
		"IRA",
		"ESG",
		"ECB",
		"Global market",
		"Asia market",
		"G20",
		"European market",
		"Brexit",
		"Interest rate",
		"Wall Street",
		"Dow Jones",
		"Nasdaq",
		"S&P 500",
		"Warren Buffett",
		"Cathie Wood",
		"Michael Burry",
		"JPMorgan",
		"Morgan Stanley",
		"Goldman Sachs",
		"BlackRock",
		"Banks",
		"Marketplace",
		"Fundamental",
		"Portfolio",
		"Bain",
		"BCG",
		"McKinsey",
		"HBR",
		"Accenture",
		"Deloitte",
		...economicSeasonal,
		...commonEconomicMoney,
	],
	Money: [
		"Investment Strategies",
		"Wealth Management",
		"Money management",
		"Stock",
		"Fund",
		"Bond",
		" Forex trading",
		"Pension",
		"ETF",
		"ELS",
		"Insurance",
		"Deposit",
		"Saving",
		"Health Insurance",
		"Employment Insurance",
		"Salary",
		"Tax savings",
		"Interest rates",
		"Credit loan",
		"Secured loan",
		"Passive Income",
		"Retire",
		"Trading",
		"Millennials",
		"Crypto",
		"Gold dollor",
		"Bitcoin",
		"Richer",
		"Ethereum",
		...moneySeasonal,
		...commonEconomicMoney,
		...commonMoneyTech,
	],
	Tech: [
		"Technology",
		"Tech Giant",
		"AI",
		"Artificial Intelligence",
		"Web 3.0",
		"Autonomous",
		"EV",
		"Metaverse",
		"Google",
		"Alphabet",
		"Microsoft",
		"Meta",
		"Amazon",
		"Tesla",
		"Apple",
		"Samsung",
		"Nvidia",
		"SpaceX",
		"OpenAI",
		"Machine Learning",
		"Startup",
		"Data science",
		"Cloud Computing",
		"Cybersecurity",
		"IoT",
		"Blockchain",
		"P2E",
		"Virtual Reality",
		"VR",
		"Augmented Reality",
		"AR Robotics 5G",
		"Quantom Computing",
		"Software",
		"Engineering",
		"Ecommerce",
		"Digitalization",
		"Subscription",
		"Platform",
		"SaaS",
		"Bankrupcy",
		"Silicon Valley",
		"Venture Capital",
		"VC",
		"Y combinator",
		"Funding",
		"Sam Altman",
		"Elon Musk",
		"Bill Gates",
		"Peter Thel",
		...techSeasonal,
		...commonMoneyTech,
	],
};
